### ISSUE TITLE
[Bug] Fixed HDMI no signal problem

### ISSUE THREAD

**Issue by ansonliao** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#1]
Some references:

https://www.insanelymac.com/forum/topic/334899-intel-framebuffer-patching-using-whatevergreen/?tab=comments#comment-2626271

https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/

https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html

**Comment by think2011** [comment]
Thanks 😀

**Comment by ansonliao** [comment]
Fixed in the latest version
