### ISSUE TITLE
Thunderbolt 3: display, charging, data transfer, no devices to verify the Daisy chaining

### ISSUE THREAD

**Issue by datouq** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#11]
雷电3 连接LG 5k 雷电显示器 不成功， 据说这个芯片不支持显示输出， 你试出来了嘛

**Comment by ansonliao** [comment]
之前试过，Type-C to HDMI的，可以输出，但要把独显的config配置改成集显的。
菊花链没试过，没有这样的硬件条件。
thunderbolt 3的数据传输是正常的，现在正在用typc-c to USB 3 hub，没问题。
