### ISSUE TITLE
成功开启雷电接口后，按睡眠按钮后会重启

### ISSUE THREAD

**Issue by heyyyss** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#24]
"UPSB(iMac19.1): thunderbolt power on failed"
楼主雷电和睡眠一起开启正常使用吗？

**Comment by ansonliao** [comment]
@iJoelyang 
这是什么log来的？
我的雷电和睡眠都没有问题？
请问你的硬件配置是什么？

**Comment by heyyyss** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/29031715/164589530-22ecd95d-eb96-4509-acde-5c2dde08ada1.png">
主板一样，bios版本也一样，只要点击左上角苹果标志下的睡眠按钮就会出现这个情况

**Comment by ansonliao** [comment]
@iJoelyang 
什么CPU？
如果CPU不是i5 9600K，你需要做ACPI/SSDT。
我推荐，就算是同一款CPU（i5 9600K），最好还是针对自己的CPU重新检查下SSDT是不是正确的

**Comment by heyyyss** [comment]
i9-9900k的cpu 确实ssdt这块感觉有点问题，我再尝试一下，非常感谢

**Comment by ansonliao** [comment]
@iJoelyang 
那你是用了我的EFI出现的问题，还是你用别人的EFI出现的问题？
