### ISSUE TITLE
ACPI里的补丁引导windows11蓝屏

### ISSUE THREAD

**Issue by leodx6313** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#50]
用你的efi通过OC引导双系统，进windows11会蓝屏，显示ACPI_BIOS_ERORR错误。经反复试验发现是ACPI里的Patch
补丁最后两项（Fixed dGPU RX 5500 XT performance；change _E2C to XE2C for TB hotplug）
造成的，不知道能不能解决。希望帮帮忙。

**Comment by ansonliao** [comment]
@leodx6313 
My Hackintosh only macOS, not multiple-booted build (such as macOS + Linux, macOS + Windows), so I can't provide any help on your issue.

Thanks.
