### ISSUE TITLE
Adapter for BCM943602CD?

### ISSUE THREAD

**Issue by nishyp** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#51]
Hi, as someone who has a similar build I just wanted to know what adapter you used for the BCM943602CD?

**Comment by ansonliao** [comment]
@nishyp , 
This one, you can buy it one from Taobao, it's cheap, only 10RMB, the keyword is "M.2 NGFF".

<img width="601" alt="image" src="https://user-images.githubusercontent.com/6060224/213376132-f095401c-4402-48f3-8c0a-70b7958a0c10.png">

**Comment by ansonliao** [comment]
@nishyp , you can check this adapter's installation by the link below, kindly check the header image of the article.
https://icyleaf.com/2019/03/asrock-z390-gaming-itx-install-hackintosh-tutorial/
