### ISSUE TITLE
Bluetooth does not work upon wake from sleep

### ISSUE THREAD

**Issue by cigarsucker** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#62]
Bluetooth does not work upon wake from sleep.

Bluetooth can be restored by restarting via terminal " sudo pkill bluetoothd".

Recent versions of macOS are said to have broken Bluetooth upon wake even for real Macs.

I have used your EFI and dropped the GPU kext and patch, since I have a compatible GPU.

Does Sleep work for you?

**Comment by ansonliao** [comment]
Hi @cigarsucker , please check: https://github.com/Mintimate/SleepAndAutoBluetoothAndWifi
