### ISSUE TITLE
Please share your bios settings

### ISSUE THREAD

**Issue by cigarsucker** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#66]
I'm having trouble with shutdown just hanging and unable to wake from keyboard or mouse keypress. I'm using bios version 4.40c. 

Could you please share your bios settings?

Many thanks.

**Comment by ansonliao** [comment]
Hi @cigarsucker , please check:
- [BIOS Configurations](https://github.com/ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX/tree/dev#BIOS-Configurations)

**Comment by cigarsucker** [comment]
Thanks @ansonliao. I updated to 4.40H a while ago, then rolled back to 4.40C. I am using all the same bios settings. I'm starting to wonder if I've got some weird bios issue happening since I can't wake from usb keyboard press or shutdown. 

I might try rolling back to stock rather beta bios 4.40 to see if these resolve the issue.

**Comment by ansonliao** [comment]
Hi @cigarsucker , 
My wake up need to press the physical power button of the machine as I don't want to wake up the mac by keyboard or mouse, if you want to wake up by keyboard or mouse, maybe you check some BIOS configurations on keyboard and mouse.
