### ISSUE TITLE
驱动雷雳使用AMD 5000系列显卡睡眠问题

### ISSUE THREAD

**Issue by Hush-vv** [ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX#7]
想问一下你这里驱动雷雳使用AMD 5000系列显卡睡眠唤醒会不会KP？

**Comment by ansonliao** [comment]
@Hush-vv 
到现在为止，还没有碰到这方面的问题，前几天还试过10几个小时的睡眠

**Comment by Hush-vv** [comment]
> @Hush-vv> 到现在为止，还没有碰到这方面的问题，也试了10个多月的睡眠睡眠稳定不使用SSDT-RX-5500-XT-Version_1_0.aml和DAGPM.kext吗？

**Comment by Hush-vv** [comment]
> @Hush-vv
> 到现在为止，还没有碰到这方面的问题，也试了10几个小时的睡眠

在不使用SSDT-RX-5500-XT-Version_1_0.aml和DAGPM.kext下也可以稳定吗？
[KP info.zip](https://github.com/ansonliao/EFI-ASRock-Z390-Phantom-Gaming-ITX/files/5846397/KP.info.zip)

**Comment by ansonliao** [comment]
1. 
首先要明白`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`的用途：
`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`是用来改善显卡在黑果下面的性能的，可以参考tonmacx86的贴子
https://www.tonymacx86.com/threads/amd-radeon-performance-enhanced-ssdt.296555/

2.
如果缺少`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`会不会有问题？
我觉得亮机和正常视频信号输出肯定是没问题的。

再来是，如果缺少`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`能不能稳定使用？
按照逻辑，应该说加了`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`这两个文件，能否稳定使用，就这个问题，在我的机器上使用这两个文件，没碰到过任何问题，不过和我对显卡的使用有关，我不处理视频制作的任务。

再再下来就是你的问题了，没有`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`这两个文件的情况下，使用蓝宝石RX 5500 XT 8GB显卡能不能稳定地使用？
这个我也没有经验，因为这显卡买回来没多久就已经配合`SSDT-RX-5500-XT-Version_1_0.aml`和`DAGPM.kext`使用了。

3.
请问 `KP` 是什么意思？

**Comment by ansonliao** [comment]
@Hush-vv 
看了你上传的log，tb3还真没碰到问题。
你的板子也是asrock z390 gaming phantom itx/ac么？

**Comment by ansonliao** [comment]
@Hush-vv 
如果你习惯问问题然后不了了之的，以后请在这个repo慎重开issue，谢谢！
本人很讨厌没有交待和不会跟进的人。

**Comment by Hush-vv** [comment]
> @ hush-vv
> 看了你上传的日志，tb3还真没碰到问题。
> 你的板子也是asrock z390游戏幻影itx / ac么？

抱歉满其他事去了，没有及时看您的回复。是一样的板子，和fangf一样
